// Comprehensive vehicle database with makes, models, and year ranges
export interface VehicleModel {
  name: string
  bodyType: string
  yearStart: number
  yearEnd?: number // undefined means still in production
  category: string
}

export interface VehicleMake {
  name: string
  category: string
  models: VehicleModel[]
}

export const vehicleDatabase: VehicleMake[] = [
  // CARS & TRUCKS
  {
    name: "Acura",
    category: "cars-trucks",
    models: [
      { name: "CL", bodyType: "Coupe", yearStart: 1997, yearEnd: 2003, category: "cars-trucks" },
      { name: "CSX", bodyType: "Sedan", yearStart: 2006, yearEnd: 2011, category: "cars-trucks" },
      { name: "EL", bodyType: "Sedan", yearStart: 1997, yearEnd: 2005, category: "cars-trucks" },
      { name: "ILX", bodyType: "Sedan", yearStart: 2013, category: "cars-trucks" },
      { name: "Integra", bodyType: "Coupe", yearStart: 1990, yearEnd: 2001, category: "cars-trucks" },
      { name: "Integra", bodyType: "Hatchback", yearStart: 2022, category: "cars-trucks" },
      { name: "Legend", bodyType: "Sedan", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "MDX", bodyType: "SUV", yearStart: 2001, category: "cars-trucks" },
      { name: "NSX", bodyType: "Coupe", yearStart: 1991, yearEnd: 2005, category: "cars-trucks" },
      { name: "NSX", bodyType: "Coupe", yearStart: 2016, yearEnd: 2022, category: "cars-trucks" },
      { name: "RDX", bodyType: "SUV", yearStart: 2007, category: "cars-trucks" },
      { name: "RL", bodyType: "Sedan", yearStart: 1996, yearEnd: 2012, category: "cars-trucks" },
      { name: "RLX", bodyType: "Sedan", yearStart: 2014, yearEnd: 2020, category: "cars-trucks" },
      { name: "RSX", bodyType: "Coupe", yearStart: 2002, yearEnd: 2006, category: "cars-trucks" },
      { name: "SLX", bodyType: "SUV", yearStart: 1996, yearEnd: 1999, category: "cars-trucks" },
      { name: "TL", bodyType: "Sedan", yearStart: 1996, yearEnd: 2014, category: "cars-trucks" },
      { name: "TLX", bodyType: "Sedan", yearStart: 2015, category: "cars-trucks" },
      { name: "TSX", bodyType: "Sedan", yearStart: 2004, yearEnd: 2014, category: "cars-trucks" },
      { name: "Vigor", bodyType: "Sedan", yearStart: 1992, yearEnd: 1994, category: "cars-trucks" },
      { name: "ZDX", bodyType: "SUV", yearStart: 2010, yearEnd: 2013, category: "cars-trucks" },
    ],
  },
  {
    name: "Audi",
    category: "cars-trucks",
    models: [
      { name: "100", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "200", bodyType: "Sedan", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "80", bodyType: "Sedan", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "90", bodyType: "Sedan", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "A3", bodyType: "Hatchback", yearStart: 2006, yearEnd: 2013, category: "cars-trucks" },
      { name: "A3", bodyType: "Sedan", yearStart: 2015, category: "cars-trucks" },
      { name: "A4", bodyType: "Sedan", yearStart: 1996, category: "cars-trucks" },
      { name: "A4 Allroad", bodyType: "Wagon", yearStart: 2013, category: "cars-trucks" },
      { name: "A5", bodyType: "Coupe", yearStart: 2008, category: "cars-trucks" },
      { name: "A6", bodyType: "Sedan", yearStart: 1995, category: "cars-trucks" },
      { name: "A6 Allroad", bodyType: "Wagon", yearStart: 2001, yearEnd: 2005, category: "cars-trucks" },
      { name: "A6 Allroad", bodyType: "Wagon", yearStart: 2013, category: "cars-trucks" },
      { name: "A7", bodyType: "Hatchback", yearStart: 2012, category: "cars-trucks" },
      { name: "A8", bodyType: "Sedan", yearStart: 1997, category: "cars-trucks" },
      { name: "Allroad", bodyType: "Wagon", yearStart: 2001, yearEnd: 2005, category: "cars-trucks" },
      { name: "Cabriolet", bodyType: "Convertible", yearStart: 1994, yearEnd: 1998, category: "cars-trucks" },
      { name: "Coupe", bodyType: "Coupe", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "e-tron", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "e-tron GT", bodyType: "Sedan", yearStart: 2022, category: "cars-trucks" },
      { name: "Q3", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "Q4 e-tron", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Q5", bodyType: "SUV", yearStart: 2009, category: "cars-trucks" },
      { name: "Q7", bodyType: "SUV", yearStart: 2007, category: "cars-trucks" },
      { name: "Q8", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Quattro", bodyType: "Coupe", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "R8", bodyType: "Coupe", yearStart: 2008, category: "cars-trucks" },
      { name: "RS3", bodyType: "Sedan", yearStart: 2017, category: "cars-trucks" },
      { name: "RS4", bodyType: "Wagon", yearStart: 2007, yearEnd: 2008, category: "cars-trucks" },
      { name: "RS5", bodyType: "Coupe", yearStart: 2013, category: "cars-trucks" },
      { name: "RS6", bodyType: "Wagon", yearStart: 2003, yearEnd: 2004, category: "cars-trucks" },
      { name: "RS6", bodyType: "Wagon", yearStart: 2020, category: "cars-trucks" },
      { name: "RS7", bodyType: "Hatchback", yearStart: 2014, category: "cars-trucks" },
      { name: "S3", bodyType: "Sedan", yearStart: 2015, category: "cars-trucks" },
      { name: "S4", bodyType: "Sedan", yearStart: 2000, category: "cars-trucks" },
      { name: "S5", bodyType: "Coupe", yearStart: 2008, category: "cars-trucks" },
      { name: "S6", bodyType: "Sedan", yearStart: 1995, category: "cars-trucks" },
      { name: "S7", bodyType: "Hatchback", yearStart: 2013, category: "cars-trucks" },
      { name: "S8", bodyType: "Sedan", yearStart: 2001, category: "cars-trucks" },
      { name: "SQ5", bodyType: "SUV", yearStart: 2014, category: "cars-trucks" },
      { name: "SQ7", bodyType: "SUV", yearStart: 2017, category: "cars-trucks" },
      { name: "SQ8", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "TT", bodyType: "Coupe", yearStart: 2000, category: "cars-trucks" },
      { name: "TTS", bodyType: "Coupe", yearStart: 2009, category: "cars-trucks" },
      { name: "TT RS", bodyType: "Coupe", yearStart: 2012, yearEnd: 2013, category: "cars-trucks" },
      { name: "TT RS", bodyType: "Coupe", yearStart: 2018, category: "cars-trucks" },
      { name: "V8", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
    ],
  },
  {
    name: "BMW",
    category: "cars-trucks",
    models: [
      { name: "1 Series", bodyType: "Coupe", yearStart: 2008, yearEnd: 2013, category: "cars-trucks" },
      { name: "2 Series", bodyType: "Coupe", yearStart: 2014, category: "cars-trucks" },
      { name: "3 Series", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "4 Series", bodyType: "Coupe", yearStart: 2014, category: "cars-trucks" },
      { name: "5 Series", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "6 Series", bodyType: "Coupe", yearStart: 1990, yearEnd: 1989, category: "cars-trucks" },
      { name: "6 Series", bodyType: "Coupe", yearStart: 2004, yearEnd: 2018, category: "cars-trucks" },
      { name: "7 Series", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "8 Series", bodyType: "Coupe", yearStart: 1991, yearEnd: 1997, category: "cars-trucks" },
      { name: "8 Series", bodyType: "Coupe", yearStart: 2019, category: "cars-trucks" },
      { name: "i3", bodyType: "Hatchback", yearStart: 2014, yearEnd: 2022, category: "cars-trucks" },
      { name: "i4", bodyType: "Sedan", yearStart: 2022, category: "cars-trucks" },
      { name: "i7", bodyType: "Sedan", yearStart: 2023, category: "cars-trucks" },
      { name: "i8", bodyType: "Coupe", yearStart: 2014, yearEnd: 2020, category: "cars-trucks" },
      { name: "iX", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "M2", bodyType: "Coupe", yearStart: 2016, category: "cars-trucks" },
      { name: "M3", bodyType: "Sedan", yearStart: 1995, category: "cars-trucks" },
      { name: "M4", bodyType: "Coupe", yearStart: 2015, category: "cars-trucks" },
      { name: "M5", bodyType: "Sedan", yearStart: 1991, category: "cars-trucks" },
      { name: "M6", bodyType: "Coupe", yearStart: 2006, yearEnd: 2018, category: "cars-trucks" },
      { name: "M8", bodyType: "Coupe", yearStart: 2020, category: "cars-trucks" },
      { name: "X1", bodyType: "SUV", yearStart: 2013, category: "cars-trucks" },
      { name: "X2", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "X3", bodyType: "SUV", yearStart: 2004, category: "cars-trucks" },
      { name: "X4", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "X5", bodyType: "SUV", yearStart: 2000, category: "cars-trucks" },
      { name: "X6", bodyType: "SUV", yearStart: 2008, category: "cars-trucks" },
      { name: "X7", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Z3", bodyType: "Convertible", yearStart: 1996, yearEnd: 2002, category: "cars-trucks" },
      { name: "Z4", bodyType: "Convertible", yearStart: 2003, yearEnd: 2008, category: "cars-trucks" },
      { name: "Z4", bodyType: "Convertible", yearStart: 2009, yearEnd: 2016, category: "cars-trucks" },
      { name: "Z4", bodyType: "Convertible", yearStart: 2019, category: "cars-trucks" },
      { name: "Z8", bodyType: "Convertible", yearStart: 2000, yearEnd: 2003, category: "cars-trucks" },
    ],
  },
  {
    name: "Buick",
    category: "cars-trucks",
    models: [
      { name: "Cascada", bodyType: "Convertible", yearStart: 2016, yearEnd: 2019, category: "cars-trucks" },
      { name: "Century", bodyType: "Sedan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Electra", bodyType: "Sedan", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
      { name: "Enclave", bodyType: "SUV", yearStart: 2008, category: "cars-trucks" },
      { name: "Encore", bodyType: "SUV", yearStart: 2013, category: "cars-trucks" },
      { name: "Encore GX", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Envision", bodyType: "SUV", yearStart: 2016, category: "cars-trucks" },
      { name: "Estate Wagon", bodyType: "Wagon", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "LaCrosse", bodyType: "Sedan", yearStart: 2005, yearEnd: 2019, category: "cars-trucks" },
      { name: "LeSabre", bodyType: "Sedan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Lucerne", bodyType: "Sedan", yearStart: 2006, yearEnd: 2011, category: "cars-trucks" },
      { name: "Park Avenue", bodyType: "Sedan", yearStart: 1991, yearEnd: 2005, category: "cars-trucks" },
      { name: "Rainier", bodyType: "SUV", yearStart: 2004, yearEnd: 2007, category: "cars-trucks" },
      { name: "Reatta", bodyType: "Coupe", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "Regal", bodyType: "Sedan", yearStart: 1990, yearEnd: 2004, category: "cars-trucks" },
      { name: "Regal", bodyType: "Sedan", yearStart: 2011, yearEnd: 2020, category: "cars-trucks" },
      { name: "Rendezvous", bodyType: "SUV", yearStart: 2002, yearEnd: 2007, category: "cars-trucks" },
      { name: "Riviera", bodyType: "Coupe", yearStart: 1990, yearEnd: 1999, category: "cars-trucks" },
      { name: "Roadmaster", bodyType: "Sedan", yearStart: 1991, yearEnd: 1996, category: "cars-trucks" },
      { name: "Skylark", bodyType: "Sedan", yearStart: 1990, yearEnd: 1998, category: "cars-trucks" },
      { name: "Terraza", bodyType: "Minivan", yearStart: 2005, yearEnd: 2007, category: "cars-trucks" },
      { name: "Verano", bodyType: "Sedan", yearStart: 2012, yearEnd: 2017, category: "cars-trucks" },
    ],
  },
  {
    name: "Cadillac",
    category: "cars-trucks",
    models: [
      { name: "Allante", bodyType: "Convertible", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "ATS", bodyType: "Sedan", yearStart: 2013, yearEnd: 2019, category: "cars-trucks" },
      { name: "Brougham", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "CT4", bodyType: "Sedan", yearStart: 2020, category: "cars-trucks" },
      { name: "CT5", bodyType: "Sedan", yearStart: 2020, category: "cars-trucks" },
      { name: "CT6", bodyType: "Sedan", yearStart: 2016, yearEnd: 2020, category: "cars-trucks" },
      { name: "CTS", bodyType: "Sedan", yearStart: 2003, yearEnd: 2019, category: "cars-trucks" },
      { name: "DeVille", bodyType: "Sedan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "DTS", bodyType: "Sedan", yearStart: 2006, yearEnd: 2011, category: "cars-trucks" },
      { name: "ELR", bodyType: "Coupe", yearStart: 2014, yearEnd: 2016, category: "cars-trucks" },
      { name: "Escalade", bodyType: "SUV", yearStart: 1999, category: "cars-trucks" },
      { name: "Escalade ESV", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "Escalade EXT", bodyType: "Pickup Truck", yearStart: 2002, yearEnd: 2013, category: "cars-trucks" },
      { name: "Eldorado", bodyType: "Coupe", yearStart: 1990, yearEnd: 2002, category: "cars-trucks" },
      { name: "Fleetwood", bodyType: "Sedan", yearStart: 1993, yearEnd: 1996, category: "cars-trucks" },
      { name: "LYRIQ", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "Seville", bodyType: "Sedan", yearStart: 1990, yearEnd: 2004, category: "cars-trucks" },
      { name: "SRX", bodyType: "SUV", yearStart: 2004, yearEnd: 2016, category: "cars-trucks" },
      { name: "STS", bodyType: "Sedan", yearStart: 2005, yearEnd: 2011, category: "cars-trucks" },
      { name: "XLR", bodyType: "Convertible", yearStart: 2004, yearEnd: 2009, category: "cars-trucks" },
      { name: "XT4", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "XT5", bodyType: "SUV", yearStart: 2017, category: "cars-trucks" },
      { name: "XT6", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
    ],
  },
  {
    name: "Chevrolet",
    category: "cars-trucks",
    models: [
      { name: "Astro", bodyType: "Minivan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Avalanche", bodyType: "Pickup Truck", yearStart: 2002, yearEnd: 2013, category: "cars-trucks" },
      { name: "Aveo", bodyType: "Sedan", yearStart: 2004, yearEnd: 2011, category: "cars-trucks" },
      { name: "Beretta", bodyType: "Coupe", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Blazer", bodyType: "SUV", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Blazer", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Bolt EV", bodyType: "Hatchback", yearStart: 2017, category: "cars-trucks" },
      { name: "Bolt EUV", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Camaro", bodyType: "Coupe", yearStart: 1990, yearEnd: 2002, category: "cars-trucks" },
      { name: "Camaro", bodyType: "Coupe", yearStart: 2010, category: "cars-trucks" },
      { name: "Caprice", bodyType: "Sedan", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Captiva Sport", bodyType: "SUV", yearStart: 2012, yearEnd: 2015, category: "cars-trucks" },
      { name: "Cavalier", bodyType: "Sedan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "City Express", bodyType: "Van", yearStart: 2015, yearEnd: 2018, category: "cars-trucks" },
      { name: "Cobalt", bodyType: "Sedan", yearStart: 2005, yearEnd: 2010, category: "cars-trucks" },
      { name: "Colorado", bodyType: "Pickup Truck", yearStart: 2004, yearEnd: 2012, category: "cars-trucks" },
      { name: "Colorado", bodyType: "Pickup Truck", yearStart: 2015, category: "cars-trucks" },
      { name: "Corsica", bodyType: "Sedan", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Corvette", bodyType: "Coupe", yearStart: 1990, category: "cars-trucks" },
      { name: "Cruze", bodyType: "Sedan", yearStart: 2011, yearEnd: 2019, category: "cars-trucks" },
      { name: "Equinox", bodyType: "SUV", yearStart: 2005, category: "cars-trucks" },
      { name: "Express", bodyType: "Van", yearStart: 1996, category: "cars-trucks" },
      { name: "HHR", bodyType: "SUV", yearStart: 2006, yearEnd: 2011, category: "cars-trucks" },
      { name: "Impala", bodyType: "Sedan", yearStart: 2000, yearEnd: 2020, category: "cars-trucks" },
      { name: "Lumina", bodyType: "Sedan", yearStart: 1990, yearEnd: 2001, category: "cars-trucks" },
      { name: "Lumina APV", bodyType: "Minivan", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Malibu", bodyType: "Sedan", yearStart: 1997, category: "cars-trucks" },
      { name: "Metro", bodyType: "Hatchback", yearStart: 1998, yearEnd: 2001, category: "cars-trucks" },
      { name: "Monte Carlo", bodyType: "Coupe", yearStart: 1995, yearEnd: 2007, category: "cars-trucks" },
      { name: "Prizm", bodyType: "Sedan", yearStart: 1998, yearEnd: 2002, category: "cars-trucks" },
      { name: "S-10", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 2004, category: "cars-trucks" },
      { name: "Silverado 1500", bodyType: "Pickup Truck", yearStart: 1999, category: "cars-trucks" },
      { name: "Silverado 2500", bodyType: "Pickup Truck", yearStart: 1999, category: "cars-trucks" },
      { name: "Silverado 3500", bodyType: "Pickup Truck", yearStart: 1999, category: "cars-trucks" },
      { name: "Sonic", bodyType: "Sedan", yearStart: 2012, yearEnd: 2020, category: "cars-trucks" },
      { name: "Spark", bodyType: "Hatchback", yearStart: 2013, yearEnd: 2022, category: "cars-trucks" },
      { name: "SSR", bodyType: "Pickup Truck", yearStart: 2003, yearEnd: 2006, category: "cars-trucks" },
      { name: "Suburban", bodyType: "SUV", yearStart: 1990, category: "cars-trucks" },
      { name: "Tahoe", bodyType: "SUV", yearStart: 1995, category: "cars-trucks" },
      { name: "Tracker", bodyType: "SUV", yearStart: 1999, yearEnd: 2004, category: "cars-trucks" },
      { name: "TrailBlazer", bodyType: "SUV", yearStart: 2002, yearEnd: 2009, category: "cars-trucks" },
      { name: "TrailBlazer", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Traverse", bodyType: "SUV", yearStart: 2009, category: "cars-trucks" },
      { name: "Trax", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "Uplander", bodyType: "Minivan", yearStart: 2005, yearEnd: 2009, category: "cars-trucks" },
      { name: "Venture", bodyType: "Minivan", yearStart: 1997, yearEnd: 2005, category: "cars-trucks" },
      { name: "Volt", bodyType: "Sedan", yearStart: 2011, yearEnd: 2019, category: "cars-trucks" },
    ],
  },
  {
    name: "Chrysler",
    category: "cars-trucks",
    models: [
      { name: "200", bodyType: "Sedan", yearStart: 2011, yearEnd: 2017, category: "cars-trucks" },
      { name: "300", bodyType: "Sedan", yearStart: 2005, category: "cars-trucks" },
      { name: "300M", bodyType: "Sedan", yearStart: 1999, yearEnd: 2004, category: "cars-trucks" },
      { name: "Aspen", bodyType: "SUV", yearStart: 2007, yearEnd: 2009, category: "cars-trucks" },
      { name: "Cirrus", bodyType: "Sedan", yearStart: 1995, yearEnd: 2000, category: "cars-trucks" },
      { name: "Concorde", bodyType: "Sedan", yearStart: 1993, yearEnd: 2004, category: "cars-trucks" },
      { name: "Conquest", bodyType: "Coupe", yearStart: 1990, yearEnd: 1989, category: "cars-trucks" },
      { name: "Crossfire", bodyType: "Coupe", yearStart: 2004, yearEnd: 2008, category: "cars-trucks" },
      { name: "Fifth Avenue", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Imperial", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Intrepid", bodyType: "Sedan", yearStart: 1993, yearEnd: 2004, category: "cars-trucks" },
      { name: "LeBaron", bodyType: "Convertible", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "LHS", bodyType: "Sedan", yearStart: 1994, yearEnd: 2001, category: "cars-trucks" },
      { name: "New Yorker", bodyType: "Sedan", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Pacifica", bodyType: "SUV", yearStart: 2004, yearEnd: 2008, category: "cars-trucks" },
      { name: "Pacifica", bodyType: "Minivan", yearStart: 2017, category: "cars-trucks" },
      { name: "PT Cruiser", bodyType: "SUV", yearStart: 2001, yearEnd: 2010, category: "cars-trucks" },
      { name: "Sebring", bodyType: "Sedan", yearStart: 1995, yearEnd: 2010, category: "cars-trucks" },
      { name: "TC", bodyType: "Convertible", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "Town & Country", bodyType: "Minivan", yearStart: 1990, yearEnd: 2016, category: "cars-trucks" },
      { name: "Voyager", bodyType: "Minivan", yearStart: 2020, category: "cars-trucks" },
    ],
  },
  {
    name: "Dodge",
    category: "cars-trucks",
    models: [
      { name: "Avenger", bodyType: "Sedan", yearStart: 1995, yearEnd: 1999, category: "cars-trucks" },
      { name: "Avenger", bodyType: "Sedan", yearStart: 2008, yearEnd: 2014, category: "cars-trucks" },
      { name: "Caliber", bodyType: "Hatchback", yearStart: 2007, yearEnd: 2012, category: "cars-trucks" },
      { name: "Caravan", bodyType: "Minivan", yearStart: 1990, yearEnd: 2020, category: "cars-trucks" },
      { name: "Challenger", bodyType: "Coupe", yearStart: 2008, category: "cars-trucks" },
      { name: "Charger", bodyType: "Sedan", yearStart: 2006, category: "cars-trucks" },
      { name: "Colt", bodyType: "Hatchback", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Dakota", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 2011, category: "cars-trucks" },
      { name: "Dart", bodyType: "Sedan", yearStart: 2013, yearEnd: 2016, category: "cars-trucks" },
      { name: "Daytona", bodyType: "Coupe", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Durango", bodyType: "SUV", yearStart: 1998, yearEnd: 2009, category: "cars-trucks" },
      { name: "Durango", bodyType: "SUV", yearStart: 2011, category: "cars-trucks" },
      { name: "Dynasty", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Grand Caravan", bodyType: "Minivan", yearStart: 1990, yearEnd: 2020, category: "cars-trucks" },
      { name: "Hornet", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "Intrepid", bodyType: "Sedan", yearStart: 1993, yearEnd: 2004, category: "cars-trucks" },
      { name: "Journey", bodyType: "SUV", yearStart: 2009, yearEnd: 2020, category: "cars-trucks" },
      { name: "Magnum", bodyType: "Wagon", yearStart: 2005, yearEnd: 2008, category: "cars-trucks" },
      { name: "Monaco", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "Neon", bodyType: "Sedan", yearStart: 1995, yearEnd: 2005, category: "cars-trucks" },
      { name: "Nitro", bodyType: "SUV", yearStart: 2007, yearEnd: 2012, category: "cars-trucks" },
      { name: "Ram 1500", bodyType: "Pickup Truck", yearStart: 1994, yearEnd: 2010, category: "cars-trucks" },
      { name: "Ram 2500", bodyType: "Pickup Truck", yearStart: 1994, yearEnd: 2010, category: "cars-trucks" },
      { name: "Ram 3500", bodyType: "Pickup Truck", yearStart: 1994, yearEnd: 2010, category: "cars-trucks" },
      { name: "Ram 50", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Ram Van", bodyType: "Van", yearStart: 1990, yearEnd: 2003, category: "cars-trucks" },
      { name: "Ramcharger", bodyType: "SUV", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Shadow", bodyType: "Hatchback", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Spirit", bodyType: "Sedan", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "Stealth", bodyType: "Coupe", yearStart: 1991, yearEnd: 1996, category: "cars-trucks" },
      { name: "Stratus", bodyType: "Sedan", yearStart: 1995, yearEnd: 2006, category: "cars-trucks" },
      { name: "Viper", bodyType: "Coupe", yearStart: 1992, yearEnd: 2017, category: "cars-trucks" },
    ],
  },
  {
    name: "Ford",
    category: "cars-trucks",
    models: [
      { name: "Aerostar", bodyType: "Minivan", yearStart: 1990, yearEnd: 1997, category: "cars-trucks" },
      { name: "Aspire", bodyType: "Hatchback", yearStart: 1994, yearEnd: 1997, category: "cars-trucks" },
      { name: "Bronco", bodyType: "SUV", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Bronco", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Bronco II", bodyType: "SUV", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
      { name: "Bronco Sport", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "C-Max", bodyType: "Hatchback", yearStart: 2013, yearEnd: 2018, category: "cars-trucks" },
      { name: "Contour", bodyType: "Sedan", yearStart: 1995, yearEnd: 2000, category: "cars-trucks" },
      { name: "Crown Victoria", bodyType: "Sedan", yearStart: 1992, yearEnd: 2011, category: "cars-trucks" },
      { name: "E-150", bodyType: "Van", yearStart: 1990, yearEnd: 2014, category: "cars-trucks" },
      { name: "E-250", bodyType: "Van", yearStart: 1990, yearEnd: 2014, category: "cars-trucks" },
      { name: "E-350", bodyType: "Van", yearStart: 1990, yearEnd: 2014, category: "cars-trucks" },
      { name: "EcoSport", bodyType: "SUV", yearStart: 2018, yearEnd: 2022, category: "cars-trucks" },
      { name: "Edge", bodyType: "SUV", yearStart: 2007, yearEnd: 2020, category: "cars-trucks" },
      { name: "Escape", bodyType: "SUV", yearStart: 2001, category: "cars-trucks" },
      { name: "Escort", bodyType: "Sedan", yearStart: 1990, yearEnd: 2003, category: "cars-trucks" },
      { name: "Excursion", bodyType: "SUV", yearStart: 2000, yearEnd: 2005, category: "cars-trucks" },
      { name: "Expedition", bodyType: "SUV", yearStart: 1997, category: "cars-trucks" },
      { name: "Explorer", bodyType: "SUV", yearStart: 1991, category: "cars-trucks" },
      {
        name: "Explorer Sport Trac",
        bodyType: "Pickup Truck",
        yearStart: 2001,
        yearEnd: 2010,
        category: "cars-trucks",
      },
      { name: "F-150", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "F-250", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "F-350", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "Festiva", bodyType: "Hatchback", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "Fiesta", bodyType: "Hatchback", yearStart: 2011, yearEnd: 2019, category: "cars-trucks" },
      { name: "Five Hundred", bodyType: "Sedan", yearStart: 2005, yearEnd: 2007, category: "cars-trucks" },
      { name: "Flex", bodyType: "SUV", yearStart: 2009, yearEnd: 2019, category: "cars-trucks" },
      { name: "Focus", bodyType: "Sedan", yearStart: 2000, yearEnd: 2018, category: "cars-trucks" },
      { name: "Freestar", bodyType: "Minivan", yearStart: 2004, yearEnd: 2007, category: "cars-trucks" },
      { name: "Freestyle", bodyType: "SUV", yearStart: 2005, yearEnd: 2007, category: "cars-trucks" },
      { name: "Fusion", bodyType: "Sedan", yearStart: 2006, yearEnd: 2020, category: "cars-trucks" },
      { name: "GT", bodyType: "Coupe", yearStart: 2005, yearEnd: 2006, category: "cars-trucks" },
      { name: "Lightning", bodyType: "Pickup Truck", yearStart: 2022, category: "cars-trucks" },
      { name: "Maverick", bodyType: "Pickup Truck", yearStart: 2022, category: "cars-trucks" },
      { name: "Mustang", bodyType: "Coupe", yearStart: 1990, category: "cars-trucks" },
      { name: "Mustang Mach-E", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Probe", bodyType: "Coupe", yearStart: 1990, yearEnd: 1997, category: "cars-trucks" },
      { name: "Ranger", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 2011, category: "cars-trucks" },
      { name: "Ranger", bodyType: "Pickup Truck", yearStart: 2019, category: "cars-trucks" },
      { name: "Taurus", bodyType: "Sedan", yearStart: 1990, yearEnd: 2019, category: "cars-trucks" },
      { name: "Taurus X", bodyType: "SUV", yearStart: 2008, yearEnd: 2009, category: "cars-trucks" },
      { name: "Tempo", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Thunderbird", bodyType: "Coupe", yearStart: 1990, yearEnd: 1997, category: "cars-trucks" },
      { name: "Thunderbird", bodyType: "Convertible", yearStart: 2002, yearEnd: 2005, category: "cars-trucks" },
      { name: "Transit", bodyType: "Van", yearStart: 2015, category: "cars-trucks" },
      { name: "Transit Connect", bodyType: "Van", yearStart: 2010, category: "cars-trucks" },
      { name: "Windstar", bodyType: "Minivan", yearStart: 1995, yearEnd: 2003, category: "cars-trucks" },
    ],
  },
  {
    name: "GMC",
    category: "cars-trucks",
    models: [
      { name: "Acadia", bodyType: "SUV", yearStart: 2007, category: "cars-trucks" },
      { name: "Canyon", bodyType: "Pickup Truck", yearStart: 2004, yearEnd: 2012, category: "cars-trucks" },
      { name: "Canyon", bodyType: "Pickup Truck", yearStart: 2015, category: "cars-trucks" },
      { name: "Envoy", bodyType: "SUV", yearStart: 2002, yearEnd: 2009, category: "cars-trucks" },
      { name: "Hummer EV", bodyType: "Pickup Truck", yearStart: 2022, category: "cars-trucks" },
      { name: "Jimmy", bodyType: "SUV", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Safari", bodyType: "Minivan", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Savana", bodyType: "Van", yearStart: 1996, category: "cars-trucks" },
      { name: "Sierra 1500", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "Sierra 2500", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "Sierra 3500", bodyType: "Pickup Truck", yearStart: 1990, category: "cars-trucks" },
      { name: "Sonoma", bodyType: "Pickup Truck", yearStart: 1991, yearEnd: 2004, category: "cars-trucks" },
      { name: "Suburban", bodyType: "SUV", yearStart: 1990, category: "cars-trucks" },
      { name: "Terrain", bodyType: "SUV", yearStart: 2010, category: "cars-trucks" },
      { name: "Typhoon", bodyType: "SUV", yearStart: 1992, yearEnd: 1993, category: "cars-trucks" },
      { name: "Vandura", bodyType: "Van", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Yukon", bodyType: "SUV", yearStart: 1992, category: "cars-trucks" },
      { name: "Yukon XL", bodyType: "SUV", yearStart: 2000, category: "cars-trucks" },
    ],
  },
  {
    name: "Honda",
    category: "cars-trucks",
    models: [
      { name: "Accord", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Civic", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "CR-V", bodyType: "SUV", yearStart: 1997, category: "cars-trucks" },
      { name: "CR-Z", bodyType: "Coupe", yearStart: 2011, yearEnd: 2016, category: "cars-trucks" },
      { name: "Crosstour", bodyType: "SUV", yearStart: 2010, yearEnd: 2015, category: "cars-trucks" },
      { name: "Del Sol", bodyType: "Convertible", yearStart: 1993, yearEnd: 1997, category: "cars-trucks" },
      { name: "Element", bodyType: "SUV", yearStart: 2003, yearEnd: 2011, category: "cars-trucks" },
      { name: "Fit", bodyType: "Hatchback", yearStart: 2007, yearEnd: 2020, category: "cars-trucks" },
      { name: "HR-V", bodyType: "SUV", yearStart: 2016, category: "cars-trucks" },
      { name: "Insight", bodyType: "Hatchback", yearStart: 2000, yearEnd: 2006, category: "cars-trucks" },
      { name: "Insight", bodyType: "Sedan", yearStart: 2010, yearEnd: 2014, category: "cars-trucks" },
      { name: "Insight", bodyType: "Hatchback", yearStart: 2019, yearEnd: 2022, category: "cars-trucks" },
      { name: "Odyssey", bodyType: "Minivan", yearStart: 1995, category: "cars-trucks" },
      { name: "Passport", bodyType: "SUV", yearStart: 1994, yearEnd: 2002, category: "cars-trucks" },
      { name: "Passport", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Pilot", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "Prelude", bodyType: "Coupe", yearStart: 1990, yearEnd: 2001, category: "cars-trucks" },
      { name: "Ridgeline", bodyType: "Pickup Truck", yearStart: 2006, yearEnd: 2014, category: "cars-trucks" },
      { name: "Ridgeline", bodyType: "Pickup Truck", yearStart: 2017, category: "cars-trucks" },
      { name: "S2000", bodyType: "Convertible", yearStart: 2000, yearEnd: 2009, category: "cars-trucks" },
    ],
  },
  {
    name: "Hyundai",
    category: "cars-trucks",
    models: [
      { name: "Accent", bodyType: "Sedan", yearStart: 1995, category: "cars-trucks" },
      { name: "Azera", bodyType: "Sedan", yearStart: 2006, yearEnd: 2017, category: "cars-trucks" },
      { name: "Elantra", bodyType: "Sedan", yearStart: 1992, category: "cars-trucks" },
      { name: "Elantra GT", bodyType: "Hatchback", yearStart: 2013, yearEnd: 2020, category: "cars-trucks" },
      { name: "Entourage", bodyType: "Minivan", yearStart: 2007, yearEnd: 2009, category: "cars-trucks" },
      { name: "Excel", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Genesis", bodyType: "Sedan", yearStart: 2009, yearEnd: 2016, category: "cars-trucks" },
      { name: "Genesis Coupe", bodyType: "Coupe", yearStart: 2010, yearEnd: 2016, category: "cars-trucks" },
      { name: "IONIQ", bodyType: "Hatchback", yearStart: 2017, yearEnd: 2022, category: "cars-trucks" },
      { name: "IONIQ 5", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "IONIQ 6", bodyType: "Sedan", yearStart: 2023, category: "cars-trucks" },
      { name: "Kona", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "Nexo", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Palisade", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Santa Cruz", bodyType: "Pickup Truck", yearStart: 2022, category: "cars-trucks" },
      { name: "Santa Fe", bodyType: "SUV", yearStart: 2001, category: "cars-trucks" },
      { name: "Santa Fe Sport", bodyType: "SUV", yearStart: 2013, yearEnd: 2018, category: "cars-trucks" },
      { name: "Scoupe", bodyType: "Coupe", yearStart: 1991, yearEnd: 1995, category: "cars-trucks" },
      { name: "Sonata", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Tiburon", bodyType: "Coupe", yearStart: 1997, yearEnd: 2008, category: "cars-trucks" },
      { name: "Tucson", bodyType: "SUV", yearStart: 2005, category: "cars-trucks" },
      { name: "Veloster", bodyType: "Hatchback", yearStart: 2012, yearEnd: 2021, category: "cars-trucks" },
      { name: "Venue", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Veracruz", bodyType: "SUV", yearStart: 2007, yearEnd: 2012, category: "cars-trucks" },
      { name: "XG300", bodyType: "Sedan", yearStart: 2001, yearEnd: 2005, category: "cars-trucks" },
      { name: "XG350", bodyType: "Sedan", yearStart: 2002, yearEnd: 2005, category: "cars-trucks" },
    ],
  },
  {
    name: "Infiniti",
    category: "cars-trucks",
    models: [
      { name: "EX35", bodyType: "SUV", yearStart: 2008, yearEnd: 2012, category: "cars-trucks" },
      { name: "EX37", bodyType: "SUV", yearStart: 2013, yearEnd: 2013, category: "cars-trucks" },
      { name: "FX35", bodyType: "SUV", yearStart: 2003, yearEnd: 2012, category: "cars-trucks" },
      { name: "FX37", bodyType: "SUV", yearStart: 2013, yearEnd: 2013, category: "cars-trucks" },
      { name: "FX45", bodyType: "SUV", yearStart: 2003, yearEnd: 2008, category: "cars-trucks" },
      { name: "FX50", bodyType: "SUV", yearStart: 2009, yearEnd: 2013, category: "cars-trucks" },
      { name: "G20", bodyType: "Sedan", yearStart: 1991, yearEnd: 2002, category: "cars-trucks" },
      { name: "G25", bodyType: "Sedan", yearStart: 2011, yearEnd: 2012, category: "cars-trucks" },
      { name: "G35", bodyType: "Sedan", yearStart: 2003, yearEnd: 2006, category: "cars-trucks" },
      { name: "G37", bodyType: "Sedan", yearStart: 2007, yearEnd: 2013, category: "cars-trucks" },
      { name: "I30", bodyType: "Sedan", yearStart: 1996, yearEnd: 2001, category: "cars-trucks" },
      { name: "I35", bodyType: "Sedan", yearStart: 2002, yearEnd: 2004, category: "cars-trucks" },
      { name: "J30", bodyType: "Sedan", yearStart: 1993, yearEnd: 1997, category: "cars-trucks" },
      { name: "JX35", bodyType: "SUV", yearStart: 2013, yearEnd: 2013, category: "cars-trucks" },
      { name: "M30", bodyType: "Coupe", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "M35", bodyType: "Sedan", yearStart: 2006, yearEnd: 2010, category: "cars-trucks" },
      { name: "M37", bodyType: "Sedan", yearStart: 2011, yearEnd: 2013, category: "cars-trucks" },
      { name: "M45", bodyType: "Sedan", yearStart: 2003, yearEnd: 2010, category: "cars-trucks" },
      { name: "M56", bodyType: "Sedan", yearStart: 2011, yearEnd: 2013, category: "cars-trucks" },
      { name: "Q30", bodyType: "Hatchback", yearStart: 2017, yearEnd: 2019, category: "cars-trucks" },
      { name: "Q40", bodyType: "Sedan", yearStart: 2015, yearEnd: 2015, category: "cars-trucks" },
      { name: "Q45", bodyType: "Sedan", yearStart: 1990, yearEnd: 2006, category: "cars-trucks" },
      { name: "Q50", bodyType: "Sedan", yearStart: 2014, category: "cars-trucks" },
      { name: "Q60", bodyType: "Coupe", yearStart: 2014, category: "cars-trucks" },
      { name: "Q70", bodyType: "Sedan", yearStart: 2014, yearEnd: 2019, category: "cars-trucks" },
      { name: "QX30", bodyType: "SUV", yearStart: 2017, yearEnd: 2019, category: "cars-trucks" },
      { name: "QX4", bodyType: "SUV", yearStart: 1997, yearEnd: 2003, category: "cars-trucks" },
      { name: "QX50", bodyType: "SUV", yearStart: 2014, category: "cars-trucks" },
      { name: "QX55", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "QX56", bodyType: "SUV", yearStart: 2004, yearEnd: 2013, category: "cars-trucks" },
      { name: "QX60", bodyType: "SUV", yearStart: 2013, category: "cars-trucks" },
      { name: "QX70", bodyType: "SUV", yearStart: 2014, yearEnd: 2017, category: "cars-trucks" },
      { name: "QX80", bodyType: "SUV", yearStart: 2014, category: "cars-trucks" },
    ],
  },
  {
    name: "Jeep",
    category: "cars-trucks",
    models: [
      { name: "Cherokee", bodyType: "SUV", yearStart: 1990, yearEnd: 2001, category: "cars-trucks" },
      { name: "Cherokee", bodyType: "SUV", yearStart: 2014, category: "cars-trucks" },
      { name: "Comanche", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "Commander", bodyType: "SUV", yearStart: 2006, yearEnd: 2010, category: "cars-trucks" },
      { name: "Compass", bodyType: "SUV", yearStart: 2007, category: "cars-trucks" },
      { name: "Gladiator", bodyType: "Pickup Truck", yearStart: 2020, category: "cars-trucks" },
      { name: "Grand Cherokee", bodyType: "SUV", yearStart: 1993, category: "cars-trucks" },
      { name: "Grand Wagoneer", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Liberty", bodyType: "SUV", yearStart: 2002, yearEnd: 2012, category: "cars-trucks" },
      { name: "Patriot", bodyType: "SUV", yearStart: 2007, yearEnd: 2017, category: "cars-trucks" },
      { name: "Renegade", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "Wagoneer", bodyType: "SUV", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "Wagoneer", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Wrangler", bodyType: "SUV", yearStart: 1990, category: "cars-trucks" },
    ],
  },
  {
    name: "Kia",
    category: "cars-trucks",
    models: [
      { name: "Amanti", bodyType: "Sedan", yearStart: 2004, yearEnd: 2009, category: "cars-trucks" },
      { name: "Borrego", bodyType: "SUV", yearStart: 2009, yearEnd: 2009, category: "cars-trucks" },
      { name: "Cadenza", bodyType: "Sedan", yearStart: 2014, yearEnd: 2020, category: "cars-trucks" },
      { name: "Carnival", bodyType: "Minivan", yearStart: 2022, category: "cars-trucks" },
      { name: "EV6", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Forte", bodyType: "Sedan", yearStart: 2010, category: "cars-trucks" },
      { name: "K5", bodyType: "Sedan", yearStart: 2021, category: "cars-trucks" },
      { name: "K900", bodyType: "Sedan", yearStart: 2015, yearEnd: 2020, category: "cars-trucks" },
      { name: "Niro", bodyType: "SUV", yearStart: 2017, category: "cars-trucks" },
      { name: "Optima", bodyType: "Sedan", yearStart: 2001, yearEnd: 2020, category: "cars-trucks" },
      { name: "Rio", bodyType: "Sedan", yearStart: 2001, yearEnd: 2020, category: "cars-trucks" },
      { name: "Rondo", bodyType: "Minivan", yearStart: 2007, yearEnd: 2010, category: "cars-trucks" },
      { name: "Sedona", bodyType: "Minivan", yearStart: 2002, yearEnd: 2021, category: "cars-trucks" },
      { name: "Seltos", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Sephia", bodyType: "Sedan", yearStart: 1994, yearEnd: 2001, category: "cars-trucks" },
      { name: "Sorento", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "Soul", bodyType: "SUV", yearStart: 2010, category: "cars-trucks" },
      { name: "Spectra", bodyType: "Sedan", yearStart: 2000, yearEnd: 2009, category: "cars-trucks" },
      { name: "Sportage", bodyType: "SUV", yearStart: 1995, category: "cars-trucks" },
      { name: "Stinger", bodyType: "Sedan", yearStart: 2018, yearEnd: 2023, category: "cars-trucks" },
      { name: "Telluride", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
    ],
  },
  {
    name: "Lexus",
    category: "cars-trucks",
    models: [
      { name: "CT", bodyType: "Hatchback", yearStart: 2011, yearEnd: 2017, category: "cars-trucks" },
      { name: "ES", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "GS", bodyType: "Sedan", yearStart: 1993, yearEnd: 2020, category: "cars-trucks" },
      { name: "GX", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "HS", bodyType: "Sedan", yearStart: 2010, yearEnd: 2012, category: "cars-trucks" },
      { name: "IS", bodyType: "Sedan", yearStart: 2001, category: "cars-trucks" },
      { name: "LC", bodyType: "Coupe", yearStart: 2018, category: "cars-trucks" },
      { name: "LFA", bodyType: "Coupe", yearStart: 2012, yearEnd: 2012, category: "cars-trucks" },
      { name: "LS", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "LX", bodyType: "SUV", yearStart: 1996, category: "cars-trucks" },
      { name: "NX", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "RC", bodyType: "Coupe", yearStart: 2015, category: "cars-trucks" },
      { name: "RX", bodyType: "SUV", yearStart: 1999, category: "cars-trucks" },
      { name: "RZ", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "SC", bodyType: "Convertible", yearStart: 1992, yearEnd: 2010, category: "cars-trucks" },
      { name: "UX", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
    ],
  },
  {
    name: "Lincoln",
    category: "cars-trucks",
    models: [
      { name: "Aviator", bodyType: "SUV", yearStart: 2003, yearEnd: 2005, category: "cars-trucks" },
      { name: "Aviator", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Blackwood", bodyType: "Pickup Truck", yearStart: 2002, yearEnd: 2003, category: "cars-trucks" },
      { name: "Continental", bodyType: "Sedan", yearStart: 1990, yearEnd: 2002, category: "cars-trucks" },
      { name: "Continental", bodyType: "Sedan", yearStart: 2017, yearEnd: 2020, category: "cars-trucks" },
      { name: "Corsair", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "LS", bodyType: "Sedan", yearStart: 2000, yearEnd: 2006, category: "cars-trucks" },
      { name: "Mark LT", bodyType: "Pickup Truck", yearStart: 2006, yearEnd: 2008, category: "cars-trucks" },
      { name: "Mark VII", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "Mark VIII", bodyType: "Coupe", yearStart: 1993, yearEnd: 1998, category: "cars-trucks" },
      { name: "MKC", bodyType: "SUV", yearStart: 2015, yearEnd: 2019, category: "cars-trucks" },
      { name: "MKS", bodyType: "Sedan", yearStart: 2009, yearEnd: 2016, category: "cars-trucks" },
      { name: "MKT", bodyType: "SUV", yearStart: 2010, yearEnd: 2019, category: "cars-trucks" },
      { name: "MKX", bodyType: "SUV", yearStart: 2007, yearEnd: 2019, category: "cars-trucks" },
      { name: "MKZ", bodyType: "Sedan", yearStart: 2007, yearEnd: 2020, category: "cars-trucks" },
      { name: "Nautilus", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "Navigator", bodyType: "SUV", yearStart: 1998, category: "cars-trucks" },
      { name: "Town Car", bodyType: "Sedan", yearStart: 1990, yearEnd: 2011, category: "cars-trucks" },
      { name: "Zephyr", bodyType: "Sedan", yearStart: 2006, yearEnd: 2006, category: "cars-trucks" },
    ],
  },
  {
    name: "Mazda",
    category: "cars-trucks",
    models: [
      { name: "323", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "626", bodyType: "Sedan", yearStart: 1990, yearEnd: 2002, category: "cars-trucks" },
      { name: "929", bodyType: "Sedan", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "B-Series", bodyType: "Pickup Truck", yearStart: 1994, yearEnd: 2009, category: "cars-trucks" },
      { name: "CX-3", bodyType: "SUV", yearStart: 2016, yearEnd: 2021, category: "cars-trucks" },
      { name: "CX-30", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "CX-5", bodyType: "SUV", yearStart: 2013, category: "cars-trucks" },
      { name: "CX-7", bodyType: "SUV", yearStart: 2007, yearEnd: 2012, category: "cars-trucks" },
      { name: "CX-9", bodyType: "SUV", yearStart: 2007, category: "cars-trucks" },
      { name: "CX-50", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "CX-90", bodyType: "SUV", yearStart: 2024, category: "cars-trucks" },
      { name: "Mazda2", bodyType: "Hatchback", yearStart: 2011, yearEnd: 2014, category: "cars-trucks" },
      { name: "Mazda3", bodyType: "Sedan", yearStart: 2004, category: "cars-trucks" },
      { name: "Mazda5", bodyType: "Minivan", yearStart: 2006, yearEnd: 2015, category: "cars-trucks" },
      { name: "Mazda6", bodyType: "Sedan", yearStart: 2003, category: "cars-trucks" },
      { name: "Millenia", bodyType: "Sedan", yearStart: 1995, yearEnd: 2002, category: "cars-trucks" },
      { name: "Miata", bodyType: "Convertible", yearStart: 1990, category: "cars-trucks" },
      { name: "MPV", bodyType: "Minivan", yearStart: 1990, yearEnd: 2006, category: "cars-trucks" },
      { name: "MX-3", bodyType: "Coupe", yearStart: 1992, yearEnd: 1995, category: "cars-trucks" },
      { name: "MX-5 Miata", bodyType: "Convertible", yearStart: 1990, category: "cars-trucks" },
      { name: "MX-6", bodyType: "Coupe", yearStart: 1990, yearEnd: 1997, category: "cars-trucks" },
      { name: "Navajo", bodyType: "SUV", yearStart: 1991, yearEnd: 1994, category: "cars-trucks" },
      { name: "Protege", bodyType: "Sedan", yearStart: 1990, yearEnd: 2003, category: "cars-trucks" },
      { name: "RX-7", bodyType: "Coupe", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "RX-8", bodyType: "Coupe", yearStart: 2004, yearEnd: 2011, category: "cars-trucks" },
      { name: "Tribute", bodyType: "SUV", yearStart: 2001, yearEnd: 2011, category: "cars-trucks" },
    ],
  },
  {
    name: "Mercedes-Benz",
    category: "cars-trucks",
    models: [
      { name: "190E", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "A-Class", bodyType: "Sedan", yearStart: 2019, category: "cars-trucks" },
      { name: "AMG GT", bodyType: "Coupe", yearStart: 2016, category: "cars-trucks" },
      { name: "B-Class", bodyType: "Hatchback", yearStart: 2014, yearEnd: 2019, category: "cars-trucks" },
      { name: "C-Class", bodyType: "Sedan", yearStart: 1994, category: "cars-trucks" },
      { name: "CL-Class", bodyType: "Coupe", yearStart: 2000, yearEnd: 2014, category: "cars-trucks" },
      { name: "CLA-Class", bodyType: "Sedan", yearStart: 2014, category: "cars-trucks" },
      { name: "CLK-Class", bodyType: "Coupe", yearStart: 1998, yearEnd: 2009, category: "cars-trucks" },
      { name: "CLS-Class", bodyType: "Sedan", yearStart: 2006, category: "cars-trucks" },
      { name: "E-Class", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "EQB", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "EQE", bodyType: "Sedan", yearStart: 2023, category: "cars-trucks" },
      { name: "EQS", bodyType: "Sedan", yearStart: 2022, category: "cars-trucks" },
      { name: "G-Class", bodyType: "SUV", yearStart: 2002, category: "cars-trucks" },
      { name: "GL-Class", bodyType: "SUV", yearStart: 2007, yearEnd: 2016, category: "cars-trucks" },
      { name: "GLA-Class", bodyType: "SUV", yearStart: 2015, category: "cars-trucks" },
      { name: "GLB-Class", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "GLC-Class", bodyType: "SUV", yearStart: 2016, category: "cars-trucks" },
      { name: "GLE-Class", bodyType: "SUV", yearStart: 2016, category: "cars-trucks" },
      { name: "GLK-Class", bodyType: "SUV", yearStart: 2010, yearEnd: 2015, category: "cars-trucks" },
      { name: "GLS-Class", bodyType: "SUV", yearStart: 2017, category: "cars-trucks" },
      { name: "M-Class", bodyType: "SUV", yearStart: 1998, yearEnd: 2015, category: "cars-trucks" },
      { name: "Maybach S-Class", bodyType: "Sedan", yearStart: 2015, category: "cars-trucks" },
      { name: "Metris", bodyType: "Van", yearStart: 2016, category: "cars-trucks" },
      { name: "R-Class", bodyType: "Minivan", yearStart: 2006, yearEnd: 2012, category: "cars-trucks" },
      { name: "S-Class", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "SL-Class", bodyType: "Convertible", yearStart: 1990, category: "cars-trucks" },
      { name: "SLK-Class", bodyType: "Convertible", yearStart: 1998, yearEnd: 2016, category: "cars-trucks" },
      { name: "SLC-Class", bodyType: "Convertible", yearStart: 2017, yearEnd: 2020, category: "cars-trucks" },
      { name: "SLR McLaren", bodyType: "Coupe", yearStart: 2005, yearEnd: 2009, category: "cars-trucks" },
      { name: "SLS AMG", bodyType: "Coupe", yearStart: 2011, yearEnd: 2015, category: "cars-trucks" },
      { name: "Sprinter", bodyType: "Van", yearStart: 2010, category: "cars-trucks" },
    ],
  },
  {
    name: "Mitsubishi",
    category: "cars-trucks",
    models: [
      { name: "3000GT", bodyType: "Coupe", yearStart: 1991, yearEnd: 1999, category: "cars-trucks" },
      { name: "Diamante", bodyType: "Sedan", yearStart: 1992, yearEnd: 2004, category: "cars-trucks" },
      { name: "Eclipse", bodyType: "Coupe", yearStart: 1990, yearEnd: 2012, category: "cars-trucks" },
      { name: "Eclipse Cross", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "Endeavor", bodyType: "SUV", yearStart: 2004, yearEnd: 2011, category: "cars-trucks" },
      { name: "Expo", bodyType: "Minivan", yearStart: 1992, yearEnd: 1995, category: "cars-trucks" },
      { name: "Galant", bodyType: "Sedan", yearStart: 1990, yearEnd: 2012, category: "cars-trucks" },
      { name: "i-MiEV", bodyType: "Hatchback", yearStart: 2012, yearEnd: 2017, category: "cars-trucks" },
      { name: "Lancer", bodyType: "Sedan", yearStart: 2002, yearEnd: 2017, category: "cars-trucks" },
      { name: "Lancer Evolution", bodyType: "Sedan", yearStart: 2003, yearEnd: 2015, category: "cars-trucks" },
      { name: "Mirage", bodyType: "Hatchback", yearStart: 1993, yearEnd: 2002, category: "cars-trucks" },
      { name: "Mirage", bodyType: "Hatchback", yearStart: 2014, category: "cars-trucks" },
      { name: "Montero", bodyType: "SUV", yearStart: 1990, yearEnd: 2006, category: "cars-trucks" },
      { name: "Montero Sport", bodyType: "SUV", yearStart: 1997, yearEnd: 2004, category: "cars-trucks" },
      { name: "Outlander", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "Outlander Sport", bodyType: "SUV", yearStart: 2011, yearEnd: 2021, category: "cars-trucks" },
      { name: "Pickup", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "Precis", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Raider", bodyType: "Pickup Truck", yearStart: 2006, yearEnd: 2009, category: "cars-trucks" },
      { name: "Sigma", bodyType: "Sedan", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
      { name: "Starion", bodyType: "Coupe", yearStart: 1990, yearEnd: 1989, category: "cars-trucks" },
      { name: "Van", bodyType: "Van", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
    ],
  },
  {
    name: "Nissan",
    category: "cars-trucks",
    models: [
      { name: "200SX", bodyType: "Coupe", yearStart: 1995, yearEnd: 1998, category: "cars-trucks" },
      { name: "240SX", bodyType: "Coupe", yearStart: 1990, yearEnd: 1998, category: "cars-trucks" },
      { name: "300ZX", bodyType: "Coupe", yearStart: 1990, yearEnd: 1996, category: "cars-trucks" },
      { name: "350Z", bodyType: "Coupe", yearStart: 2003, yearEnd: 2009, category: "cars-trucks" },
      { name: "370Z", bodyType: "Coupe", yearStart: 2009, yearEnd: 2020, category: "cars-trucks" },
      { name: "Altima", bodyType: "Sedan", yearStart: 1993, category: "cars-trucks" },
      { name: "Armada", bodyType: "SUV", yearStart: 2004, category: "cars-trucks" },
      { name: "Ariya", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "Cube", bodyType: "SUV", yearStart: 2009, yearEnd: 2014, category: "cars-trucks" },
      { name: "Frontier", bodyType: "Pickup Truck", yearStart: 1998, category: "cars-trucks" },
      { name: "GT-R", bodyType: "Coupe", yearStart: 2009, category: "cars-trucks" },
      { name: "Juke", bodyType: "SUV", yearStart: 2011, yearEnd: 2017, category: "cars-trucks" },
      { name: "Kicks", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "Leaf", bodyType: "Hatchback", yearStart: 2011, category: "cars-trucks" },
      { name: "Maxima", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Murano", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
      { name: "NV200", bodyType: "Van", yearStart: 2013, yearEnd: 2020, category: "cars-trucks" },
      { name: "NX", bodyType: "Coupe", yearStart: 1991, yearEnd: 1993, category: "cars-trucks" },
      { name: "Pathfinder", bodyType: "SUV", yearStart: 1990, category: "cars-trucks" },
      { name: "Pickup", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 1997, category: "cars-trucks" },
      { name: "Pulsar", bodyType: "Hatchback", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
      { name: "Quest", bodyType: "Minivan", yearStart: 1993, yearEnd: 2017, category: "cars-trucks" },
      { name: "Rogue", bodyType: "SUV", yearStart: 2008, category: "cars-trucks" },
      { name: "Rogue Sport", bodyType: "SUV", yearStart: 2017, yearEnd: 2022, category: "cars-trucks" },
      { name: "Sentra", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Stanza", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "Titan", bodyType: "Pickup Truck", yearStart: 2004, category: "cars-trucks" },
      { name: "Titan XD", bodyType: "Pickup Truck", yearStart: 2016, yearEnd: 2019, category: "cars-trucks" },
      { name: "Versa", bodyType: "Sedan", yearStart: 2007, category: "cars-trucks" },
      { name: "Xterra", bodyType: "SUV", yearStart: 2000, yearEnd: 2015, category: "cars-trucks" },
      { name: "Z", bodyType: "Coupe", yearStart: 2023, category: "cars-trucks" },
    ],
  },
  {
    name: "Ram",
    category: "cars-trucks",
    models: [
      { name: "1500", bodyType: "Pickup Truck", yearStart: 2011, category: "cars-trucks" },
      { name: "2500", bodyType: "Pickup Truck", yearStart: 2011, category: "cars-trucks" },
      { name: "3500", bodyType: "Pickup Truck", yearStart: 2011, category: "cars-trucks" },
      { name: "C/V", bodyType: "Van", yearStart: 2012, yearEnd: 2015, category: "cars-trucks" },
      { name: "ProMaster", bodyType: "Van", yearStart: 2014, category: "cars-trucks" },
      { name: "ProMaster City", bodyType: "Van", yearStart: 2015, yearEnd: 2022, category: "cars-trucks" },
    ],
  },
  {
    name: "Subaru",
    category: "cars-trucks",
    models: [
      { name: "Ascent", bodyType: "SUV", yearStart: 2019, category: "cars-trucks" },
      { name: "B9 Tribeca", bodyType: "SUV", yearStart: 2006, yearEnd: 2007, category: "cars-trucks" },
      { name: "Baja", bodyType: "Pickup Truck", yearStart: 2003, yearEnd: 2006, category: "cars-trucks" },
      { name: "BRZ", bodyType: "Coupe", yearStart: 2013, category: "cars-trucks" },
      { name: "Crosstrek", bodyType: "SUV", yearStart: 2013, category: "cars-trucks" },
      { name: "Forester", bodyType: "SUV", yearStart: 1998, category: "cars-trucks" },
      { name: "Impreza", bodyType: "Sedan", yearStart: 1993, category: "cars-trucks" },
      { name: "Justy", bodyType: "Hatchback", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Legacy", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Loyale", bodyType: "Sedan", yearStart: 1990, yearEnd: 1994, category: "cars-trucks" },
      { name: "Outback", bodyType: "Wagon", yearStart: 1995, category: "cars-trucks" },
      { name: "Solterra", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "SVX", bodyType: "Coupe", yearStart: 1992, yearEnd: 1997, category: "cars-trucks" },
      { name: "Tribeca", bodyType: "SUV", yearStart: 2008, yearEnd: 2014, category: "cars-trucks" },
      { name: "WRX", bodyType: "Sedan", yearStart: 2015, category: "cars-trucks" },
      { name: "XV Crosstrek", bodyType: "SUV", yearStart: 2013, yearEnd: 2015, category: "cars-trucks" },
    ],
  },
  {
    name: "Tesla",
    category: "cars-trucks",
    models: [
      { name: "Cybertruck", bodyType: "Pickup Truck", yearStart: 2024, category: "cars-trucks" },
      { name: "Model 3", bodyType: "Sedan", yearStart: 2017, category: "cars-trucks" },
      { name: "Model S", bodyType: "Sedan", yearStart: 2012, category: "cars-trucks" },
      { name: "Model X", bodyType: "SUV", yearStart: 2016, category: "cars-trucks" },
      { name: "Model Y", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Roadster", bodyType: "Convertible", yearStart: 2008, yearEnd: 2012, category: "cars-trucks" },
    ],
  },
  {
    name: "Toyota",
    category: "cars-trucks",
    models: [
      { name: "4Runner", bodyType: "SUV", yearStart: 1990, category: "cars-trucks" },
      { name: "86", bodyType: "Coupe", yearStart: 2017, category: "cars-trucks" },
      { name: "Avalon", bodyType: "Sedan", yearStart: 1995, category: "cars-trucks" },
      { name: "bZ4X", bodyType: "SUV", yearStart: 2023, category: "cars-trucks" },
      { name: "C-HR", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "Camry", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Celica", bodyType: "Coupe", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Corolla", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Corolla Cross", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Cressida", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "Crown", bodyType: "Sedan", yearStart: 2023, category: "cars-trucks" },
      { name: "Echo", bodyType: "Sedan", yearStart: 2000, yearEnd: 2005, category: "cars-trucks" },
      { name: "FJ Cruiser", bodyType: "SUV", yearStart: 2007, yearEnd: 2014, category: "cars-trucks" },
      { name: "GR86", bodyType: "Coupe", yearStart: 2022, category: "cars-trucks" },
      { name: "GR Corolla", bodyType: "Hatchback", yearStart: 2023, category: "cars-trucks" },
      { name: "GR Supra", bodyType: "Coupe", yearStart: 2020, category: "cars-trucks" },
      { name: "Highlander", bodyType: "SUV", yearStart: 2001, category: "cars-trucks" },
      { name: "Land Cruiser", bodyType: "SUV", yearStart: 1990, yearEnd: 2021, category: "cars-trucks" },
      { name: "Land Cruiser", bodyType: "SUV", yearStart: 2024, category: "cars-trucks" },
      { name: "Matrix", bodyType: "Hatchback", yearStart: 2003, yearEnd: 2014, category: "cars-trucks" },
      { name: "MR2", bodyType: "Coupe", yearStart: 1990, yearEnd: 2005, category: "cars-trucks" },
      { name: "Paseo", bodyType: "Coupe", yearStart: 1992, yearEnd: 1999, category: "cars-trucks" },
      { name: "Pickup", bodyType: "Pickup Truck", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "Previa", bodyType: "Minivan", yearStart: 1991, yearEnd: 1997, category: "cars-trucks" },
      { name: "Prius", bodyType: "Hatchback", yearStart: 2001, category: "cars-trucks" },
      { name: "Prius c", bodyType: "Hatchback", yearStart: 2012, yearEnd: 2019, category: "cars-trucks" },
      { name: "Prius Prime", bodyType: "Hatchback", yearStart: 2017, category: "cars-trucks" },
      { name: "Prius v", bodyType: "Wagon", yearStart: 2012, yearEnd: 2017, category: "cars-trucks" },
      { name: "RAV4", bodyType: "SUV", yearStart: 1996, category: "cars-trucks" },
      { name: "RAV4 Prime", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Sequoia", bodyType: "SUV", yearStart: 2001, category: "cars-trucks" },
      { name: "Sienna", bodyType: "Minivan", yearStart: 1998, category: "cars-trucks" },
      { name: "Solara", bodyType: "Coupe", yearStart: 1999, yearEnd: 2008, category: "cars-trucks" },
      { name: "Supra", bodyType: "Coupe", yearStart: 1993, yearEnd: 1998, category: "cars-trucks" },
      { name: "T100", bodyType: "Pickup Truck", yearStart: 1993, yearEnd: 1998, category: "cars-trucks" },
      { name: "Tacoma", bodyType: "Pickup Truck", yearStart: 1995, category: "cars-trucks" },
      { name: "Tercel", bodyType: "Sedan", yearStart: 1990, yearEnd: 1999, category: "cars-trucks" },
      { name: "Tundra", bodyType: "Pickup Truck", yearStart: 2000, category: "cars-trucks" },
      { name: "Van", bodyType: "Van", yearStart: 1990, yearEnd: 1989, category: "cars-trucks" },
      { name: "Venza", bodyType: "SUV", yearStart: 2009, yearEnd: 2015, category: "cars-trucks" },
      { name: "Venza", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Yaris", bodyType: "Hatchback", yearStart: 2007, yearEnd: 2020, category: "cars-trucks" },
      { name: "Yaris iA", bodyType: "Sedan", yearStart: 2017, yearEnd: 2018, category: "cars-trucks" },
    ],
  },
  {
    name: "Volkswagen",
    category: "cars-trucks",
    models: [
      { name: "Arteon", bodyType: "Sedan", yearStart: 2019, category: "cars-trucks" },
      { name: "Atlas", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "Atlas Cross Sport", bodyType: "SUV", yearStart: 2020, category: "cars-trucks" },
      { name: "Beetle", bodyType: "Hatchback", yearStart: 1998, yearEnd: 2019, category: "cars-trucks" },
      { name: "Cabrio", bodyType: "Convertible", yearStart: 1995, yearEnd: 2002, category: "cars-trucks" },
      { name: "Cabriolet", bodyType: "Convertible", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "CC", bodyType: "Sedan", yearStart: 2009, yearEnd: 2017, category: "cars-trucks" },
      { name: "Corrado", bodyType: "Coupe", yearStart: 1990, yearEnd: 1995, category: "cars-trucks" },
      { name: "Eos", bodyType: "Convertible", yearStart: 2007, yearEnd: 2016, category: "cars-trucks" },
      { name: "Eurovan", bodyType: "Van", yearStart: 1993, yearEnd: 2003, category: "cars-trucks" },
      { name: "Fox", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "GLI", bodyType: "Sedan", yearStart: 2019, category: "cars-trucks" },
      { name: "Golf", bodyType: "Hatchback", yearStart: 1990, category: "cars-trucks" },
      { name: "Golf R", bodyType: "Hatchback", yearStart: 2012, category: "cars-trucks" },
      { name: "GTI", bodyType: "Hatchback", yearStart: 1990, category: "cars-trucks" },
      { name: "ID.4", bodyType: "SUV", yearStart: 2021, category: "cars-trucks" },
      { name: "Jetta", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Passat", bodyType: "Sedan", yearStart: 1990, category: "cars-trucks" },
      { name: "Phaeton", bodyType: "Sedan", yearStart: 2004, yearEnd: 2006, category: "cars-trucks" },
      { name: "Rabbit", bodyType: "Hatchback", yearStart: 2006, yearEnd: 2009, category: "cars-trucks" },
      { name: "Routan", bodyType: "Minivan", yearStart: 2009, yearEnd: 2014, category: "cars-trucks" },
      { name: "Taos", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "Tiguan", bodyType: "SUV", yearStart: 2009, category: "cars-trucks" },
      { name: "Touareg", bodyType: "SUV", yearStart: 2004, category: "cars-trucks" },
      { name: "Vanagon", bodyType: "Van", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
    ],
  },
  {
    name: "Volvo",
    category: "cars-trucks",
    models: [
      { name: "240", bodyType: "Sedan", yearStart: 1990, yearEnd: 1993, category: "cars-trucks" },
      { name: "740", bodyType: "Sedan", yearStart: 1990, yearEnd: 1992, category: "cars-trucks" },
      { name: "760", bodyType: "Sedan", yearStart: 1990, yearEnd: 1990, category: "cars-trucks" },
      { name: "780", bodyType: "Coupe", yearStart: 1990, yearEnd: 1991, category: "cars-trucks" },
      { name: "850", bodyType: "Sedan", yearStart: 1993, yearEnd: 1997, category: "cars-trucks" },
      { name: "940", bodyType: "Sedan", yearStart: 1991, yearEnd: 1995, category: "cars-trucks" },
      { name: "960", bodyType: "Sedan", yearStart: 1992, yearEnd: 1997, category: "cars-trucks" },
      { name: "C30", bodyType: "Hatchback", yearStart: 2008, yearEnd: 2013, category: "cars-trucks" },
      { name: "C40", bodyType: "SUV", yearStart: 2022, category: "cars-trucks" },
      { name: "C70", bodyType: "Convertible", yearStart: 1998, yearEnd: 2013, category: "cars-trucks" },
      { name: "S40", bodyType: "Sedan", yearStart: 2000, yearEnd: 2011, category: "cars-trucks" },
      { name: "S60", bodyType: "Sedan", yearStart: 2001, category: "cars-trucks" },
      { name: "S70", bodyType: "Sedan", yearStart: 1998, yearEnd: 2000, category: "cars-trucks" },
      { name: "S80", bodyType: "Sedan", yearStart: 1999, yearEnd: 2016, category: "cars-trucks" },
      { name: "S90", bodyType: "Sedan", yearStart: 1997, yearEnd: 1998, category: "cars-trucks" },
      { name: "S90", bodyType: "Sedan", yearStart: 2017, category: "cars-trucks" },
      { name: "V40", bodyType: "Wagon", yearStart: 2013, yearEnd: 2019, category: "cars-trucks" },
      { name: "V50", bodyType: "Wagon", yearStart: 2005, yearEnd: 2011, category: "cars-trucks" },
      { name: "V60", bodyType: "Wagon", yearStart: 2011, category: "cars-trucks" },
      { name: "V70", bodyType: "Wagon", yearStart: 1998, yearEnd: 2016, category: "cars-trucks" },
      { name: "V90", bodyType: "Wagon", yearStart: 1997, yearEnd: 1998, category: "cars-trucks" },
      { name: "V90", bodyType: "Wagon", yearStart: 2017, category: "cars-trucks" },
      { name: "XC40", bodyType: "SUV", yearStart: 2018, category: "cars-trucks" },
      { name: "XC60", bodyType: "SUV", yearStart: 2008, category: "cars-trucks" },
      { name: "XC70", bodyType: "Wagon", yearStart: 2003, yearEnd: 2016, category: "cars-trucks" },
      { name: "XC90", bodyType: "SUV", yearStart: 2003, category: "cars-trucks" },
    ],
  },

  // MOTORCYCLES
  {
    name: "Harley-Davidson",
    category: "motorcycles",
    models: [
      { name: "Sportster 883", bodyType: "Cruiser", yearStart: 1990, yearEnd: 2022, category: "motorcycles" },
      { name: "Sportster 1200", bodyType: "Cruiser", yearStart: 1990, yearEnd: 2022, category: "motorcycles" },
      { name: "Sportster S", bodyType: "Cruiser", yearStart: 2021, category: "motorcycles" },
      { name: "Street 500", bodyType: "Standard", yearStart: 2014, yearEnd: 2020, category: "motorcycles" },
      { name: "Street 750", bodyType: "Standard", yearStart: 2014, yearEnd: 2020, category: "motorcycles" },
      { name: "Street Bob", bodyType: "Cruiser", yearStart: 2006, category: "motorcycles" },
      { name: "Fat Bob", bodyType: "Cruiser", yearStart: 2008, category: "motorcycles" },
      { name: "Low Rider", bodyType: "Cruiser", yearStart: 1990, category: "motorcycles" },
      { name: "Softail", bodyType: "Cruiser", yearStart: 1990, category: "motorcycles" },
      { name: "Heritage Softail", bodyType: "Cruiser", yearStart: 1990, category: "motorcycles" },
      { name: "Fat Boy", bodyType: "Cruiser", yearStart: 1990, category: "motorcycles" },
      { name: "Breakout", bodyType: "Cruiser", yearStart: 2013, category: "motorcycles" },
      { name: "Deluxe", bodyType: "Cruiser", yearStart: 2005, category: "motorcycles" },
      { name: "Electra Glide", bodyType: "Touring", yearStart: 1990, category: "motorcycles" },
      { name: "Road King", bodyType: "Touring", yearStart: 1994, category: "motorcycles" },
      { name: "Road Glide", bodyType: "Touring", yearStart: 1998, category: "motorcycles" },
      { name: "Street Glide", bodyType: "Touring", yearStart: 2006, category: "motorcycles" },
      { name: "Ultra Limited", bodyType: "Touring", yearStart: 2010, category: "motorcycles" },
      { name: "LiveWire", bodyType: "Electric", yearStart: 2019, category: "motorcycles" },
      { name: "Pan America", bodyType: "Adventure", yearStart: 2021, category: "motorcycles" },
    ],
  },
  {
    name: "Honda",
    category: "motorcycles",
    models: [
      { name: "CBR600RR", bodyType: "Sport", yearStart: 2003, category: "motorcycles" },
      { name: "CBR1000RR", bodyType: "Sport", yearStart: 2004, category: "motorcycles" },
      { name: "CBR300R", bodyType: "Sport", yearStart: 2015, category: "motorcycles" },
      { name: "CBR500R", bodyType: "Sport", yearStart: 2013, category: "motorcycles" },
      { name: "CB300R", bodyType: "Standard", yearStart: 2018, category: "motorcycles" },
      { name: "CB500F", bodyType: "Standard", yearStart: 2013, category: "motorcycles" },
      { name: "CB650R", bodyType: "Standard", yearStart: 2019, category: "motorcycles" },
      { name: "CB1000R", bodyType: "Standard", yearStart: 2018, category: "motorcycles" },
      { name: "Rebel 300", bodyType: "Cruiser", yearStart: 2017, category: "motorcycles" },
      { name: "Rebel 500", bodyType: "Cruiser", yearStart: 2017, category: "motorcycles" },
      { name: "Rebel 1100", bodyType: "Cruiser", yearStart: 2021, category: "motorcycles" },
      { name: "Shadow", bodyType: "Cruiser", yearStart: 1990, yearEnd: 2020, category: "motorcycles" },
      { name: "Fury", bodyType: "Cruiser", yearStart: 2010, yearEnd: 2019, category: "motorcycles" },
      { name: "Gold Wing", bodyType: "Touring", yearStart: 1990, category: "motorcycles" },
      { name: "Africa Twin", bodyType: "Adventure", yearStart: 2016, category: "motorcycles" },
      { name: "CRF250L", bodyType: "Dual Sport", yearStart: 2013, category: "motorcycles" },
      { name: "CRF450L", bodyType: "Dual Sport", yearStart: 2019, category: "motorcycles" },
      { name: "CRF250R", bodyType: "Dirt Bike", yearStart: 2004, category: "motorcycles" },
      { name: "CRF450R", bodyType: "Dirt Bike", yearStart: 2002, category: "motorcycles" },
      { name: "Grom", bodyType: "Standard", yearStart: 2014, category: "motorcycles" },
      { name: "Monkey", bodyType: "Standard", yearStart: 2019, category: "motorcycles" },
      { name: "Trail 125", bodyType: "Standard", yearStart: 2021, category: "motorcycles" },
    ],
  },
  {
    name: "Yamaha",
    category: "motorcycles",
    models: [
      { name: "YZF-R1", bodyType: "Sport", yearStart: 1998, category: "motorcycles" },
      { name: "YZF-R6", bodyType: "Sport", yearStart: 1999, category: "motorcycles" },
      { name: "YZF-R3", bodyType: "Sport", yearStart: 2015, category: "motorcycles" },
      { name: "YZF-R7", bodyType: "Sport", yearStart: 2022, category: "motorcycles" },
      { name: "MT-03", bodyType: "Standard", yearStart: 2016, category: "motorcycles" },
      { name: "MT-07", bodyType: "Standard", yearStart: 2014, category: "motorcycles" },
      { name: "MT-09", bodyType: "Standard", yearStart: 2014, category: "motorcycles" },
      { name: "MT-10", bodyType: "Standard", yearStart: 2016, category: "motorcycles" },
      { name: "FZ-07", bodyType: "Standard", yearStart: 2015, yearEnd: 2017, category: "motorcycles" },
      { name: "FZ-09", bodyType: "Standard", yearStart: 2014, yearEnd: 2017, category: "motorcycles" },
      { name: "Bolt", bodyType: "Cruiser", yearStart: 2014, category: "motorcycles" },
      { name: "V Star 250", bodyType: "Cruiser", yearStart: 2008, yearEnd: 2020, category: "motorcycles" },
      { name: "V Star 650", bodyType: "Cruiser", yearStart: 1998, yearEnd: 2017, category: "motorcycles" },
      { name: "V Star 950", bodyType: "Cruiser", yearStart: 2009, yearEnd: 2017, category: "motorcycles" },
      { name: "V Star 1300", bodyType: "Cruiser", yearStart: 2007, yearEnd: 2017, category: "motorcycles" },
      { name: "Road Star", bodyType: "Cruiser", yearStart: 1999, yearEnd: 2009, category: "motorcycles" },
      { name: "Raider", bodyType: "Cruiser", yearStart: 2008, yearEnd: 2017, category: "motorcycles" },
      { name: "Stryker", bodyType: "Cruiser", yearStart: 2011, yearEnd: 2017, category: "motorcycles" },
      { name: "FJR1300", bodyType: "Touring", yearStart: 2003, category: "motorcycles" },
      { name: "Super Ténéré", bodyType: "Adventure", yearStart: 2012, yearEnd: 2020, category: "motorcycles" },
      { name: "Ténéré 700", bodyType: "Adventure", yearStart: 2021, category: "motorcycles" },
      { name: "WR250R", bodyType: "Dual Sport", yearStart: 2008, yearEnd: 2020, category: "motorcycles" },
      { name: "WR450F", bodyType: "Dirt Bike", yearStart: 2003, category: "motorcycles" },
      { name: "YZ250F", bodyType: "Dirt Bike", yearStart: 2001, category: "motorcycles" },
      { name: "YZ450F", bodyType: "Dirt Bike", yearStart: 2003, category: "motorcycles" },
      { name: "TW200", bodyType: "Dual Sport", yearStart: 1990, category: "motorcycles" },
      { name: "XT250", bodyType: "Dual Sport", yearStart: 2008, category: "motorcycles" },
    ],
  },
  {
    name: "Kawasaki",
    category: "motorcycles",
    models: [
      { name: "Ninja ZX-10R", bodyType: "Sport", yearStart: 2004, category: "motorcycles" },
      { name: "Ninja ZX-6R", bodyType: "Sport", yearStart: 1995, category: "motorcycles" },
      { name: "Ninja 400", bodyType: "Sport", yearStart: 2018, category: "motorcycles" },
      { name: "Ninja 650", bodyType: "Sport", yearStart: 2006, category: "motorcycles" },
      { name: "Ninja 1000", bodyType: "Sport", yearStart: 2011, category: "motorcycles" },
      { name: "Ninja H2", bodyType: "Sport", yearStart: 2015, category: "motorcycles" },
      { name: "Z125 Pro", bodyType: "Standard", yearStart: 2017, category: "motorcycles" },
      { name: "Z400", bodyType: "Standard", yearStart: 2019, category: "motorcycles" },
      { name: "Z650", bodyType: "Standard", yearStart: 2017, category: "motorcycles" },
      { name: "Z900", bodyType: "Standard", yearStart: 2017, category: "motorcycles" },
      { name: "Z1000", bodyType: "Standard", yearStart: 2003, yearEnd: 2020, category: "motorcycles" },
      { name: "Vulcan S", bodyType: "Cruiser", yearStart: 2015, category: "motorcycles" },
      { name: "Vulcan 650", bodyType: "Cruiser", yearStart: 2006, yearEnd: 2008, category: "motorcycles" },
      { name: "Vulcan 900", bodyType: "Cruiser", yearStart: 2006, yearEnd: 2020, category: "motorcycles" },
      { name: "Vulcan 1700", bodyType: "Cruiser", yearStart: 2009, yearEnd: 2020, category: "motorcycles" },
      { name: "Mean Streak", bodyType: "Cruiser", yearStart: 2002, yearEnd: 2008, category: "motorcycles" },
      { name: "Concours 14", bodyType: "Touring", yearStart: 2008, category: "motorcycles" },
      { name: "Versys 300", bodyType: "Adventure", yearStart: 2017, category: "motorcycles" },
      { name: "Versys 650", bodyType: "Adventure", yearStart: 2007, category: "motorcycles" },
      { name: "Versys 1000", bodyType: "Adventure", yearStart: 2012, category: "motorcycles" },
      { name: "KLR650", bodyType: "Dual Sport", yearStart: 1990, category: "motorcycles" },
      { name: "KLX250", bodyType: "Dual Sport", yearStart: 2009, category: "motorcycles" },
      { name: "KX250", bodyType: "Dirt Bike", yearStart: 1990, category: "motorcycles" },
      { name: "KX450", bodyType: "Dirt Bike", yearStart: 2006, category: "motorcycles" },
      { name: "KX250F", bodyType: "Dirt Bike", yearStart: 2004, category: "motorcycles" },
      { name: "KX450F", bodyType: "Dirt Bike", yearStart: 2006, category: "motorcycles" },
    ],
  },
  {
    name: "Suzuki",
    category: "motorcycles",
    models: [
      { name: "GSX-R1000", bodyType: "Sport", yearStart: 2001, category: "motorcycles" },
      { name: "GSX-R750", bodyType: "Sport", yearStart: 1990, category: "motorcycles" },
      { name: "GSX-R600", bodyType: "Sport", yearStart: 1997, category: "motorcycles" },
      { name: "GSX250R", bodyType: "Sport", yearStart: 2017, category: "motorcycles" },
      { name: "Hayabusa", bodyType: "Sport", yearStart: 1999, category: "motorcycles" },
      { name: "SV650", bodyType: "Standard", yearStart: 1999, category: "motorcycles" },
      { name: "GSX-S750", bodyType: "Standard", yearStart: 2015, category: "motorcycles" },
      { name: "GSX-S1000", bodyType: "Standard", yearStart: 2015, category: "motorcycles" },
      { name: "TU250X", bodyType: "Standard", yearStart: 2009, yearEnd: 2020, category: "motorcycles" },
      { name: "Boulevard M109R", bodyType: "Cruiser", yearStart: 2006, yearEnd: 2019, category: "motorcycles" },
      { name: "Boulevard M90", bodyType: "Cruiser", yearStart: 2009, yearEnd: 2020, category: "motorcycles" },
      { name: "Boulevard M50", bodyType: "Cruiser", yearStart: 2005, yearEnd: 2020, category: "motorcycles" },
      { name: "Boulevard C90", bodyType: "Cruiser", yearStart: 2005, yearEnd: 2020, category: "motorcycles" },
      { name: "Boulevard C50", bodyType: "Cruiser", yearStart: 2005, yearEnd: 2020, category: "motorcycles" },
      { name: "Intruder", bodyType: "Cruiser", yearStart: 1990, yearEnd: 2004, category: "motorcycles" },
      { name: "Marauder", bodyType: "Cruiser", yearStart: 1997, yearEnd: 2004, category: "motorcycles" },
      { name: "V-Strom 650", bodyType: "Adventure", yearStart: 2004, category: "motorcycles" },
      { name: "V-Strom 1000", bodyType: "Adventure", yearStart: 2002, category: "motorcycles" },
      { name: "V-Strom 1050", bodyType: "Adventure", yearStart: 2020, category: "motorcycles" },
      { name: "DR650S", bodyType: "Dual Sport", yearStart: 1990, category: "motorcycles" },
      { name: "DR-Z400S", bodyType: "Dual Sport", yearStart: 2000, category: "motorcycles" },
      { name: "RM-Z250", bodyType: "Dirt Bike", yearStart: 2004, category: "motorcycles" },
      { name: "RM-Z450", bodyType: "Dirt Bike", yearStart: 2005, category: "motorcycles" },
      { name: "RMX450Z", bodyType: "Dual Sport", yearStart: 2010, yearEnd: 2011, category: "motorcycles" },
    ],
  },

  // RVS
  {
    name: "Winnebago",
    category: "rvs",
    models: [
      { name: "Brave", bodyType: "Class A", yearStart: 1990, yearEnd: 2003, category: "rvs" },
      { name: "Adventurer", bodyType: "Class A", yearStart: 1990, yearEnd: 2020, category: "rvs" },
      { name: "Vista", bodyType: "Class A", yearStart: 2004, category: "rvs" },
      { name: "Sunstar", bodyType: "Class A", yearStart: 2005, category: "rvs" },
      { name: "Journey", bodyType: "Class A", yearStart: 2008, category: "rvs" },
      { name: "Forza", bodyType: "Class A", yearStart: 2014, category: "rvs" },
      { name: "Intent", bodyType: "Class A", yearStart: 2020, category: "rvs" },
      { name: "Rialta", bodyType: "Class C", yearStart: 1996, yearEnd: 2005, category: "rvs" },
      { name: "Aspect", bodyType: "Class C", yearStart: 2005, yearEnd: 2020, category: "rvs" },
      { name: "View", bodyType: "Class C", yearStart: 2008, category: "rvs" },
      { name: "Navion", bodyType: "Class C", yearStart: 2009, category: "rvs" },
      { name: "Fuse", bodyType: "Class C", yearStart: 2015, category: "rvs" },
      { name: "Travato", bodyType: "Class B", yearStart: 2014, category: "rvs" },
      { name: "Revel", bodyType: "Class B", yearStart: 2018, category: "rvs" },
      { name: "Solis", bodyType: "Class B", yearStart: 2020, category: "rvs" },
      { name: "Boldt", bodyType: "Class B", yearStart: 2021, category: "rvs" },
      { name: "Minnie Winnie", bodyType: "Class C", yearStart: 1990, category: "rvs" },
      { name: "Micro Minnie", bodyType: "Travel Trailer", yearStart: 2014, category: "rvs" },
      { name: "Minnie", bodyType: "Travel Trailer", yearStart: 2000, category: "rvs" },
      { name: "Minnie Plus", bodyType: "Travel Trailer", yearStart: 2018, category: "rvs" },
    ],
  },
  {
    name: "Thor",
    category: "rvs",
    models: [
      { name: "Ace", bodyType: "Class A", yearStart: 2013, category: "rvs" },
      { name: "Palazzo", bodyType: "Class A", yearStart: 2008, category: "rvs" },
      { name: "Tuscany", bodyType: "Class A", yearStart: 2005, category: "rvs" },
      { name: "Venetian", bodyType: "Class A", yearStart: 2007, yearEnd: 2012, category: "rvs" },
      { name: "Windsport", bodyType: "Class A", yearStart: 2010, category: "rvs" },
      { name: "Hurricane", bodyType: "Class A", yearStart: 1990, category: "rvs" },
      { name: "Outlaw", bodyType: "Class A", yearStart: 2006, category: "rvs" },
      { name: "Challenger", bodyType: "Class A", yearStart: 2015, category: "rvs" },
      { name: "A.C.E", bodyType: "Class A", yearStart: 2013, category: "rvs" },
      { name: "Chateau", bodyType: "Class C", yearStart: 1990, category: "rvs" },
      { name: "Four Winds", bodyType: "Class C", yearStart: 1990, category: "rvs" },
      { name: "Majestic", bodyType: "Class C", yearStart: 2005, yearEnd: 2020, category: "rvs" },
      { name: "Quantum", bodyType: "Class C", yearStart: 2015, category: "rvs" },
      { name: "Compass", bodyType: "Travel Trailer", yearStart: 2017, category: "rvs" },
      { name: "Freedom Elite", bodyType: "Travel Trailer", yearStart: 2018, category: "rvs" },
      { name: "Gemini", bodyType: "Travel Trailer", yearStart: 2020, category: "rvs" },
      { name: "Tranquility", bodyType: "Travel Trailer", yearStart: 2019, category: "rvs" },
      { name: "Sequence", bodyType: "Travel Trailer", yearStart: 2021, category: "rvs" },
      { name: "Aria", bodyType: "Class B", yearStart: 2020, category: "rvs" },
      { name: "Tellaro", bodyType: "Class B", yearStart: 2021, category: "rvs" },
    ],
  },

  // BOATS
  {
    name: "Sea Ray",
    category: "boats",
    models: [
      { name: "Sundancer 260", bodyType: "Cabin Cruiser", yearStart: 1990, category: "boats" },
      { name: "Sundancer 280", bodyType: "Cabin Cruiser", yearStart: 1995, category: "boats" },
      { name: "Sundancer 300", bodyType: "Cabin Cruiser", yearStart: 2000, category: "boats" },
      { name: "Sundancer 320", bodyType: "Cabin Cruiser", yearStart: 2005, category: "boats" },
      { name: "Sundancer 350", bodyType: "Cabin Cruiser", yearStart: 2010, category: "boats" },
      { name: "Sundancer 370", bodyType: "Cabin Cruiser", yearStart: 2015, category: "boats" },
      { name: "SPX 190", bodyType: "Bowrider", yearStart: 2018, category: "boats" },
      { name: "SPX 210", bodyType: "Bowrider", yearStart: 2018, category: "boats" },
      { name: "SPX 230", bodyType: "Bowrider", yearStart: 2018, category: "boats" },
      { name: "SLX 230", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SLX 250", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SLX 280", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SLX 310", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SLX 350", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SLX 400", bodyType: "Bowrider", yearStart: 2020, category: "boats" },
      { name: "SDX 220", bodyType: "Deck Boat", yearStart: 2019, category: "boats" },
      { name: "SDX 250", bodyType: "Deck Boat", yearStart: 2019, category: "boats" },
      { name: "SDX 270", bodyType: "Deck Boat", yearStart: 2019, category: "boats" },
      { name: "SDX 290", bodyType: "Deck Boat", yearStart: 2019, category: "boats" },
      { name: "Fly 400", bodyType: "Yacht", yearStart: 2021, category: "boats" },
      { name: "Fly 460", bodyType: "Yacht", yearStart: 2021, category: "boats" },
      { name: "Fly 520", bodyType: "Yacht", yearStart: 2021, category: "boats" },
    ],
  },
  {
    name: "Boston Whaler",
    models: [
      { name: "130 Super Sport", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "150 Super Sport", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "170 Montauk", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "190 Montauk", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "210 Montauk", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "220 Dauntless", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "250 Dauntless", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "280 Dauntless", bodyType: "Center Console", yearStart: 2020, category: "boats" },
      { name: "320 Vantage", bodyType: "Dual Console", yearStart: 2020, category: "boats" },
      { name: "350 Realm", bodyType: "Cabin Cruiser", yearStart: 2020, category: "boats" },
    ],
    category: "boats",
  },
]
